# PharmaTrace Supply Chain Information Network API
#
# The PharmaTrace SCIN API provides network members a resource and process oriented access to the blockchain backed market and inventory information. It represents a layer of abstraction above the Hyperledger network to facilitate a business focused development of clients and integration systems without the need to directly connect to Hyperledger nodes.
#
# OpenAPI spec version: 0.0.1
# Contact: api@pharmatrace.io
# Generated by: https://openapi-generator.tech


#' PharmaceuticalList Class
#'
#' @field products 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PharmaceuticalList <- R6::R6Class(
  'PharmaceuticalList',
  public = list(
    `products` = NULL,
    initialize = function(`products`){
      if (!missing(`products`)) {
                stopifnot(is.vector(`products`), length(`products`) != 0)
                sapply(`products`, function(x) stopifnot(R6::is.R6(x)))
        self$`products` <- `products`
      }
    },
    toJSON = function() {
      PharmaceuticalListObject <- list()
      if (!is.null(self$`products`)) {
        PharmaceuticalListObject[['products']] <-
                sapply(self$`products`, function(x) x$toJSON())
      }

      PharmaceuticalListObject
    },
    fromJSON = function(PharmaceuticalListJson) {
      PharmaceuticalListObject <- jsonlite::fromJSON(PharmaceuticalListJson)
      if (!is.null(PharmaceuticalListObject$`products`)) {
                self$`products` <- sapply(PharmaceuticalListObject$`products`, function(x) {
                  productsObject <- Pharmaceutical$new()
                  productsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
                  productsObject
            })
      }
    },
    toJSONString = function() {
       outstring <- sprintf(
        '{
           "products":
                  ["%s"]
              
        }',
                paste0(sapply(self$`products`, function(x) x$toJSON()), collapse='","')
      )
      gsub("[\r\n]| ", "", outstring)
    },
    fromJSONString = function(PharmaceuticalListJson) {
      PharmaceuticalListObject <- jsonlite::fromJSON(PharmaceuticalListJson)
              self$`products` <- sapply(PharmaceuticalListObject$`products`, function(x) Pharmaceutical$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
