# PharmaTrace Supply Chain Information Network API
#
# The PharmaTrace SCIN API provides network members a resource and process oriented access to the blockchain backed market and inventory information. It represents a layer of abstraction above the Hyperledger network to facilitate a business focused development of clients and integration systems without the need to directly connect to Hyperledger nodes.
#
# OpenAPI spec version: 0.0.1
# Contact: api@pharmatrace.io
# Generated by: https://openapi-generator.tech


#' SystemInformation Class
#'
#' @field uuid 
#' @field language 
#' @field header 
#' @field message 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SystemInformation <- R6::R6Class(
  'SystemInformation',
  public = list(
    `uuid` = NULL,
    `language` = NULL,
    `header` = NULL,
    `message` = NULL,
    initialize = function(`uuid`, `language`, `header`, `message`){
      if (!missing(`uuid`)) {
                stopifnot(is.character(`uuid`), length(`uuid`) == 1)
        self$`uuid` <- `uuid`
      }
      if (!missing(`language`)) {
                stopifnot(is.character(`language`), length(`language`) == 1)
        self$`language` <- `language`
      }
      if (!missing(`header`)) {
                stopifnot(is.character(`header`), length(`header`) == 1)
        self$`header` <- `header`
      }
      if (!missing(`message`)) {
                stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
    },
    toJSON = function() {
      SystemInformationObject <- list()
      if (!is.null(self$`uuid`)) {
        SystemInformationObject[['uuid']] <-
                self$`uuid`
      }
      if (!is.null(self$`language`)) {
        SystemInformationObject[['language']] <-
                self$`language`
      }
      if (!is.null(self$`header`)) {
        SystemInformationObject[['header']] <-
                self$`header`
      }
      if (!is.null(self$`message`)) {
        SystemInformationObject[['message']] <-
                self$`message`
      }

      SystemInformationObject
    },
    fromJSON = function(SystemInformationJson) {
      SystemInformationObject <- jsonlite::fromJSON(SystemInformationJson)
      if (!is.null(SystemInformationObject$`uuid`)) {
                self$`uuid` <- SystemInformationObject$`uuid`
      }
      if (!is.null(SystemInformationObject$`language`)) {
                self$`language` <- SystemInformationObject$`language`
      }
      if (!is.null(SystemInformationObject$`header`)) {
                self$`header` <- SystemInformationObject$`header`
      }
      if (!is.null(SystemInformationObject$`message`)) {
                self$`message` <- SystemInformationObject$`message`
      }
    },
    toJSONString = function() {
       outstring <- sprintf(
        '{
           "uuid":
                      
                      "%s"
                  
              ,
           "language":
                      
                      "%s"
                  
              ,
           "header":
                      
                      "%s"
                  
              ,
           "message":
                      
                      "%s"
                  
              
        }',
                self$`uuid`,
                self$`language`,
                self$`header`,
                self$`message`
      )
      gsub("[\r\n]| ", "", outstring)
    },
    fromJSONString = function(SystemInformationJson) {
      SystemInformationObject <- jsonlite::fromJSON(SystemInformationJson)
              self$`uuid` <- SystemInformationObject$`uuid`
              self$`language` <- SystemInformationObject$`language`
              self$`header` <- SystemInformationObject$`header`
              self$`message` <- SystemInformationObject$`message`
    }
  )
)
